# Generated by Django 2.1.3 on 2018-11-24 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0012_auto_20181118_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='num_child_elements',
        ),
        migrations.RemoveField(
            model_name='group',
            name='num_child_groups',
        ),
    ]
